# Site settings
title: "The Adventures of Seán"
author: "Seán Mythen"
description: "This is Seán Mythen's personal website.  Here you can stay up to date with his ramblings and adventures!"
keywords: "Science, Computers, Programming, Video Games, Music, Tesla, Android, Unreal."
colophon: "© MMXVII by Seán Mythen"

baseurl: ""
url: "http://seanmythen.net"


simple_search: http://google.com/search
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title
google-analytics: UA-64778303-6

email: mythen.sean@gmail.com
github_username: SeanMythen

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
